[package]
name = "ashleyclarkson/default"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "dev"

[dependencies]
Knit = "sleitnick/knit@^1"
Trove = "sleitnick/trove@^1"
Signal = "sleitnick/signal@^1"
TableUtil = "sleitnick/table-util@^1"
Promise = "evaera/promise@^3"
Fusion = "elttob/fusion@^0.2"

[server-dependencies]
ProfileService = "alreadypro/profileservice@^1"